# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

import ccxt.async_support
from ccxt.async_support.base.ws.cache import ArrayCache, ArrayCacheBySymbolById, ArrayCacheByTimestamp
from ccxt.base.types import Any, Balances, Int, Order, OrderBook, Position, Str, Strings, Ticker, Tickers, Trade
from ccxt.async_support.base.ws.client import Client
from typing import List


class aster(ccxt.async_support.aster):

    def describe(self) -> Any:
        return self.deep_extend(super(aster, self).describe(), {
            'has': {
                'ws': True,
                'watchBalance': True,
                'watchMyTrades': True,
                'watchOHLCV': True,
                'watchOrderBook': True,
                'watchOrders': True,
                'watchPositions': True,
                'watchTicker': True,
                'watchTickers': True,
                'watchTrades': True,
                'watchTradesForSymbols': True,
            },
            'urls': {
                'api': {
                    'ws': 'wss://fstream.asterdex.com/ws',
                },
            },
            'options': {
                'tradesLimit': 1000,
                'ordersLimit': 1000,
                'OHLCVLimit': 1000,
                'watchOrderBookRate': 100,
                'watchOrderBookLimit': 1000,
                'listenKeyRefreshRate': 1200000,
                'ws': {
                    'cost': 1,
                },
            },
            'streaming': {
                'keepAlive': 30000,
                'ping': self.ping,
            },
        })

    async def watch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        """
        watches information on open orders with bid(buy) and ask(sell) prices, volumes and other data
        :param str symbol: unified symbol of the market to fetch the order book for
        :param int [limit]: the maximum amount of order book entries to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: A dictionary of `order book structures <https://docs.ccxt.com/#/?id=order-book-structure>` indexed by market symbols
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        url = self.urls['api']['ws']
        marketId = market['id']
        messageHash = 'orderbook:' + symbol
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': [
                marketId.lower() + '@depth@100ms',
            ],
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        orderbook = await self.watch(url, messageHash, message, messageHash)
        return orderbook.limit()

    def handle_order_book(self, client: Client, message):
        #
        #     {
        #         "e": "depthUpdate",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "U": 12345678,
        #         "u": 12345679,
        #         "b": [
        #             ["50000.00", "1.5"]
        #         ],
        #         "a": [
        #             ["50100.00", "0.5"]
        #         ]
        #     }
        #
        marketId = self.safe_string(message, 's')
        market = self.safe_market(marketId)
        symbol = market['symbol']
        timestamp = self.safe_integer(message, 'E')
        bids = self.safe_list(message, 'b', [])
        asks = self.safe_list(message, 'a', [])
        snapshot = self.parse_order_book({
            'bids': bids,
            'asks': asks,
        }, symbol, timestamp)
        if not (symbol in self.orderbooks):
            ob = self.order_book(snapshot)
            self.orderbooks[symbol] = ob
        orderbook = self.orderbooks[symbol]
        orderbook.reset(snapshot)
        messageHash = 'orderbook:' + symbol
        client.resolve(orderbook, messageHash)

    async def watch_trades(self, symbol: str, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        watches information on multiple trades made in a market
        :param str symbol: unified market symbol of the market trades were made in
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trade structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        url = self.urls['api']['ws']
        marketId = market['id']
        messageHash = 'trades:' + symbol
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': [
                marketId.lower() + '@aggTrade',
            ],
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        trades = await self.watch(url, messageHash, message, messageHash)
        if self.newUpdates:
            limit = trades.getLimit(symbol, limit)
        return self.filter_by_symbol_since_limit(trades, symbol, since, limit, True)

    async def watch_trades_for_symbols(self, symbols: List[str], since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        watches information on multiple trades made in multiple markets
        :param str[] symbols: unified market symbols of the markets trades were made in
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trade structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        await self.load_markets()
        symbols = self.market_symbols(symbols)
        url = self.urls['api']['ws']
        messageHashes = []
        subscriptions = []
        for i in range(0, len(symbols)):
            symbol = symbols[i]
            market = self.market(symbol)
            marketId = market['id']
            messageHash = 'trades:' + symbol
            messageHashes.append(messageHash)
            subscriptions.append(marketId.lower() + '@aggTrade')
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': subscriptions,
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        trades = await self.watch_multiple(url, messageHashes, message, messageHashes)
        if self.newUpdates:
            first = self.safe_dict(trades, 0)
            tradeSymbol = self.safe_string(first, 'symbol')
            limit = trades.getLimit(tradeSymbol, limit)
        return self.filter_by_symbols_since_limit(trades, symbols, since, limit, True)

    def handle_trades(self, client: Client, message):
        #
        #     {
        #         "e": "aggTrade",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "a": 12345,
        #         "p": "50000.00",
        #         "q": "1.5",
        #         "f": 12344,
        #         "l": 12345,
        #         "T": 1638747327000,
        #         "m": False
        #     }
        #
        marketId = self.safe_string(message, 's')
        market = self.safe_market(marketId)
        symbol = market['symbol']
        trade = self.parse_ws_trade(message, market)
        messageHash = 'trades:' + symbol
        tradesArray = self.safe_value(self.trades, symbol)
        if tradesArray is None:
            limit = self.safe_integer(self.options, 'tradesLimit', 1000)
            tradesArray = ArrayCache(limit)
            self.trades[symbol] = tradesArray
        tradesArray.append(trade)
        client.resolve(tradesArray, messageHash)

    def parse_ws_trade(self, trade, market=None):
        #
        #     {
        #         "e": "aggTrade",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "a": 12345,
        #         "p": "50000.00",
        #         "q": "1.5",
        #         "f": 12344,
        #         "l": 12345,
        #         "T": 1638747327000,
        #         "m": False
        #     }
        #
        id = self.safe_string(trade, 'a')
        timestamp = self.safe_integer(trade, 'T')
        price = self.safe_string(trade, 'p')
        amount = self.safe_string(trade, 'q')
        marketId = self.safe_string(trade, 's')
        market = self.safe_market(marketId, market)
        symbol = market['symbol']
        side = 'sell' if self.safe_value(trade, 'm') else 'buy'
        return self.safe_trade({
            'info': trade,
            'id': id,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': None,
            'side': side,
            'order': None,
            'takerOrMaker': None,
            'price': price,
            'amount': amount,
            'cost': None,
            'fee': None,
        }, market)

    async def watch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        url = self.urls['api']['ws']
        marketId = market['id']
        messageHash = 'ticker:' + symbol
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': [
                marketId.lower() + '@ticker',
            ],
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        return await self.watch(url, messageHash, message, messageHash)

    async def watch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
        :param str[] symbols: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        await self.load_markets()
        symbols = self.market_symbols(symbols)
        url = self.urls['api']['ws']
        messageHash = 'tickers'
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': [
                'not ticker@arr',
            ],
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        tickers = await self.watch(url, messageHash, message, messageHash)
        if self.newUpdates:
            return self.filter_by_array_tickers(tickers, 'symbol', symbols)
        return self.tickers

    def handle_ticker(self, client: Client, message):
        #
        #     {
        #         "e": "24hrTicker",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "p": "1000.00",
        #         "P": "2.00",
        #         "w": "49500.00",
        #         "c": "50000.00",
        #         "Q": "1.5",
        #         "o": "49000.00",
        #         "h": "51000.00",
        #         "l": "48000.00",
        #         "v": "10000.0",
        #         "q": "495000000.0",
        #         "O": 1638660928000,
        #         "C": 1638747328000,
        #         "F": 12340,
        #         "L": 12345,
        #         "n": 6
        #     }
        #
        marketId = self.safe_string(message, 's')
        market = self.safe_market(marketId)
        symbol = market['symbol']
        ticker = self.parse_ws_ticker(message, market)
        self.tickers[symbol] = ticker
        messageHash = 'ticker:' + symbol
        client.resolve(ticker, messageHash)

    def handle_tickers(self, client: Client, message):
        #
        #     [
        #         {
        #             "e": "24hrTicker",
        #             "E": 1638747328000,
        #             "s": "BTCUSDT",
        #             ...
        #         }
        #     ]
        #
        tickers = self.safe_list(message, 'data', [])
        parsedTickers = {}
        for i in range(0, len(tickers)):
            ticker = tickers[i]
            marketId = self.safe_string(ticker, 's')
            market = self.safe_market(marketId)
            symbol = market['symbol']
            parsedTicker = self.parse_ws_ticker(ticker, market)
            self.tickers[symbol] = parsedTicker
            parsedTickers[symbol] = parsedTicker
        messageHash = 'tickers'
        client.resolve(self.tickers, messageHash)

    def parse_ws_ticker(self, ticker, market=None) -> Ticker:
        #
        #     {
        #         "e": "24hrTicker",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "p": "1000.00",
        #         "P": "2.00",
        #         "w": "49500.00",
        #         "c": "50000.00",
        #         "Q": "1.5",
        #         "o": "49000.00",
        #         "h": "51000.00",
        #         "l": "48000.00",
        #         "v": "10000.0",
        #         "q": "495000000.0",
        #         "O": 1638660928000,
        #         "C": 1638747328000,
        #         "F": 12340,
        #         "L": 12345,
        #         "n": 6
        #     }
        #
        timestamp = self.safe_integer(ticker, 'E')
        marketId = self.safe_string(ticker, 's')
        market = self.safe_market(marketId, market)
        symbol = market['symbol']
        last = self.safe_string(ticker, 'c')
        open = self.safe_string(ticker, 'o')
        high = self.safe_string(ticker, 'h')
        low = self.safe_string(ticker, 'l')
        baseVolume = self.safe_string(ticker, 'v')
        quoteVolume = self.safe_string(ticker, 'q')
        change = self.safe_string(ticker, 'p')
        percentage = self.safe_string(ticker, 'P')
        vwap = self.safe_string(ticker, 'w')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': high,
            'low': low,
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': vwap,
            'open': open,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': quoteVolume,
            'info': ticker,
        }, market)

    async def watch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        watches historical candlestick data containing the open, high, low, and close price, and the volume of a market
        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str timeframe: the length of time each candle represents
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum amount of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        await self.load_markets()
        market = self.market(symbol)
        symbol = market['symbol']
        url = self.urls['api']['ws']
        marketId = market['id']
        interval = self.safe_string(self.timeframes, timeframe, timeframe)
        messageHash = 'ohlcv:' + timeframe + ':' + symbol
        request: dict = {
            'method': 'SUBSCRIBE',
            'params': [
                marketId.lower() + '@kline_' + interval,
            ],
            'id': self.request_id(),
        }
        message = self.extend(request, params)
        ohlcv = await self.watch(url, messageHash, message, messageHash)
        if self.newUpdates:
            limit = ohlcv.getLimit(symbol, limit)
        return self.filter_by_since_limit(ohlcv, since, limit, 0, True)

    def handle_ohlcv(self, client: Client, message):
        #
        #     {
        #         "e": "kline",
        #         "E": 1638747328000,
        #         "s": "BTCUSDT",
        #         "k": {
        #             "t": 1638747300000,
        #             "T": 1638747359999,
        #             "s": "BTCUSDT",
        #             "i": "1m",
        #             "f": 12340,
        #             "L": 12345,
        #             "o": "49000.00",
        #             "c": "50000.00",
        #             "h": "51000.00",
        #             "l": "48000.00",
        #             "v": "10000.0",
        #             "n": 6,
        #             "x": False,
        #             "q": "495000000.0",
        #             "V": "5000.0",
        #             "Q": "247500000.0"
        #         }
        #     }
        #
        kline = self.safe_dict(message, 'k', {})
        marketId = self.safe_string(kline, 's')
        market = self.safe_market(marketId)
        symbol = market['symbol']
        interval = self.safe_string(kline, 'i')
        timeframe = self.find_timeframe(interval)
        parsed = [
            self.safe_integer(kline, 't'),
            self.safe_number(kline, 'o'),
            self.safe_number(kline, 'h'),
            self.safe_number(kline, 'l'),
            self.safe_number(kline, 'c'),
            self.safe_number(kline, 'v'),
        ]
        messageHash = 'ohlcv:' + timeframe + ':' + symbol
        self.ohlcvs[symbol] = self.safe_dict(self.ohlcvs, symbol, {})
        stored = self.safe_value(self.ohlcvs[symbol], timeframe)
        if stored is None:
            limit = self.safe_integer(self.options, 'OHLCVLimit', 1000)
            stored = ArrayCacheByTimestamp(limit)
            self.ohlcvs[symbol][timeframe] = stored
        stored.append(parsed)
        client.resolve(stored, messageHash)

    async def watch_balance(self, params={}) -> Balances:
        """
        watch balance and get the amount of funds available for trading or funds locked in orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `balance structure <https://docs.ccxt.com/#/?id=balance-structure>`
        """
        await self.load_markets()
        await self.authenticate(params)
        url = self.urls['api']['ws']
        listenKey = self.safe_string(self.options, 'listenKey')
        messageHash = 'balance'
        return await self.watch(url + '/' + listenKey, messageHash, None, messageHash)

    def handle_balance(self, client: Client, message):
        #
        #     {
        #         "e": "ACCOUNT_UPDATE",
        #         "E": 1638747328000,
        #         "a": {
        #             "B": [
        #                 {
        #                     "a": "USDT",
        #                     "wb": "10000.00000000",
        #                     "cw": "9500.00000000"
        #                 }
        #             ]
        #         }
        #     }
        #
        accountData = self.safe_dict(message, 'a', {})
        balances = self.safe_list(accountData, 'B', [])
        for i in range(0, len(balances)):
            balance = balances[i]
            currencyId = self.safe_string(balance, 'a')
            code = self.safe_currency_code(currencyId)
            account = self.account()
            account['free'] = self.safe_string(balance, 'cw')
            account['total'] = self.safe_string(balance, 'wb')
            self.balance[code] = account
        self.balance = self.safe_balance(self.balance)
        messageHash = 'balance'
        client.resolve(self.balance, messageHash)

    async def watch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        watches information on multiple orders made by the user
        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        await self.load_markets()
        await self.authenticate(params)
        url = self.urls['api']['ws']
        listenKey = self.safe_string(self.options, 'listenKey')
        messageHash = 'orders'
        if symbol is not None:
            symbol = self.symbol(symbol)
            messageHash += ':' + symbol
        orders = await self.watch(url + '/' + listenKey, messageHash, None, messageHash)
        if self.newUpdates:
            limit = orders.getLimit(symbol, limit)
        return self.filter_by_symbol_since_limit(orders, symbol, since, limit, True)

    def handle_order(self, client: Client, message):
        #
        #     {
        #         "e": "ORDER_TRADE_UPDATE",
        #         "E": 1638747328000,
        #         "o": {
        #             "s": "BTCUSDT",
        #             "c": "client_order_id",
        #             "S": "BUY",
        #             "o": "LIMIT",
        #             "f": "GTC",
        #             "q": "1.5",
        #             "p": "50000.00",
        #             "ap": "0",
        #             "sp": "0",
        #             "x": "NEW",
        #             "X": "NEW",
        #             "i": 12345,
        #             "l": "0",
        #             "z": "0",
        #             "L": "0",
        #             "T": 1638747327000,
        #             "t": 0
        #         }
        #     }
        #
        orderData = self.safe_dict(message, 'o', {})
        order = self.parse_ws_order(orderData)
        symbol = order['symbol']
        if self.orders is None:
            limit = self.safe_integer(self.options, 'ordersLimit', 1000)
            self.orders = ArrayCacheBySymbolById(limit)
        orders = self.orders
        orders.append(order)
        messageHash = 'orders'
        client.resolve(orders, messageHash)
        messageHash += ':' + symbol
        client.resolve(orders, messageHash)

    def parse_ws_order(self, order, market=None):
        #
        #     {
        #         "s": "BTCUSDT",
        #         "c": "client_order_id",
        #         "S": "BUY",
        #         "o": "LIMIT",
        #         "f": "GTC",
        #         "q": "1.5",
        #         "p": "50000.00",
        #         "ap": "0",
        #         "sp": "0",
        #         "x": "NEW",
        #         "X": "NEW",
        #         "i": 12345,
        #         "l": "0",
        #         "z": "0",
        #         "L": "0",
        #         "T": 1638747327000,
        #         "t": 0
        #     }
        #
        id = self.safe_string(order, 'i')
        clientOrderId = self.safe_string(order, 'c')
        marketId = self.safe_string(order, 's')
        market = self.safe_market(marketId, market)
        symbol = market['symbol']
        side = self.safe_string_lower(order, 'S')
        type = self.safe_string_lower(order, 'o')
        price = self.safe_string(order, 'p')
        amount = self.safe_string(order, 'q')
        filled = self.safe_string(order, 'z')
        average = self.safe_string(order, 'ap')
        timestamp = self.safe_integer(order, 'T')
        rawStatus = self.safe_string(order, 'X')
        status = self.parse_order_status(rawStatus)
        timeInForce = self.safe_string(order, 'f')
        return self.safe_order({
            'info': order,
            'id': id,
            'clientOrderId': clientOrderId,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': None,
            'symbol': symbol,
            'type': type,
            'side': side,
            'price': price,
            'amount': amount,
            'cost': None,
            'average': average,
            'filled': filled,
            'remaining': None,
            'status': status,
            'fee': None,
            'trades': None,
            'timeInForce': timeInForce,
            'postOnly': None,
            'reduceOnly': None,
        }, market)

    async def watch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        watches information on multiple trades made by the user
        :param str symbol: unified market symbol of the market trades were made in
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trade structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `trade structures <https://docs.ccxt.com/#/?id=trade-structure>`
        """
        await self.load_markets()
        await self.authenticate(params)
        url = self.urls['api']['ws']
        listenKey = self.safe_string(self.options, 'listenKey')
        messageHash = 'myTrades'
        if symbol is not None:
            symbol = self.symbol(symbol)
            messageHash += ':' + symbol
        trades = await self.watch(url + '/' + listenKey, messageHash, None, messageHash)
        if self.newUpdates:
            limit = trades.getLimit(symbol, limit)
        return self.filter_by_symbol_since_limit(trades, symbol, since, limit, True)

    def handle_my_trade(self, client: Client, message):
        #
        #     {
        #         "e": "ORDER_TRADE_UPDATE",
        #         "E": 1638747328000,
        #         "o": {
        #             "s": "BTCUSDT",
        #             "c": "client_order_id",
        #             "S": "BUY",
        #             "o": "LIMIT",
        #             "f": "GTC",
        #             "q": "1.5",
        #             "p": "50000.00",
        #             "x": "TRADE",
        #             "X": "PARTIALLY_FILLED",
        #             "i": 12345,
        #             "l": "1.0",
        #             "z": "1.0",
        #             "L": "50000.00",
        #             "n": "10.00",
        #             "N": "USDT",
        #             "T": 1638747327000,
        #             "t": 67890
        #         }
        #     }
        #
        orderData = self.safe_dict(message, 'o', {})
        executionType = self.safe_string(orderData, 'x')
        if executionType != 'TRADE':
            return
        trade = self.parse_ws_my_trade(orderData)
        symbol = trade['symbol']
        if self.myTrades is None:
            limit = self.safe_integer(self.options, 'tradesLimit', 1000)
            self.myTrades = ArrayCacheBySymbolById(limit)
        myTrades = self.myTrades
        myTrades.append(trade)
        messageHash = 'myTrades'
        client.resolve(myTrades, messageHash)
        messageHash += ':' + symbol
        client.resolve(myTrades, messageHash)

    def parse_ws_my_trade(self, trade, market=None):
        #
        #     {
        #         "s": "BTCUSDT",
        #         "c": "client_order_id",
        #         "S": "BUY",
        #         "o": "LIMIT",
        #         "l": "1.0",
        #         "z": "1.0",
        #         "L": "50000.00",
        #         "n": "10.00",
        #         "N": "USDT",
        #         "T": 1638747327000,
        #         "t": 67890,
        #         "i": 12345
        #     }
        #
        id = self.safe_string(trade, 't')
        orderId = self.safe_string(trade, 'i')
        marketId = self.safe_string(trade, 's')
        market = self.safe_market(marketId, market)
        symbol = market['symbol']
        side = self.safe_string_lower(trade, 'S')
        type = self.safe_string_lower(trade, 'o')
        price = self.safe_string(trade, 'L')
        amount = self.safe_string(trade, 'l')
        timestamp = self.safe_integer(trade, 'T')
        feeCost = self.safe_string(trade, 'n')
        feeCurrency = self.safe_currency_code(self.safe_string(trade, 'N'))
        fee = None
        if feeCost is not None:
            fee = {
                'cost': feeCost,
                'currency': feeCurrency,
            }
        return self.safe_trade({
            'info': trade,
            'id': id,
            'order': orderId,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': type,
            'side': side,
            'takerOrMaker': None,
            'price': price,
            'amount': amount,
            'cost': None,
            'fee': fee,
        }, market)

    async def watch_positions(self, symbols: Strings = None, since: Int = None, limit: Int = None, params={}) -> List[Position]:
        """
        watch all open positions
        :param str[] [symbols]: list of unified market symbols
        :param int [since]: the earliest time in ms to fetch positions for
        :param int [limit]: the maximum number of positions to retrieve
        :param dict params: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `position structure <https://docs.ccxt.com/en/latest/manual.html#position-structure>`
        """
        await self.load_markets()
        await self.authenticate(params)
        url = self.urls['api']['ws']
        listenKey = self.safe_string(self.options, 'listenKey')
        messageHash = 'positions'
        positions = await self.watch(url + '/' + listenKey, messageHash, None, messageHash)
        return self.filter_by_symbols_since_limit(positions, symbols, since, limit, True)

    def handle_position(self, client: Client, message):
        #
        #     {
        #         "e": "ACCOUNT_UPDATE",
        #         "E": 1638747328000,
        #         "a": {
        #             "P": [
        #                 {
        #                     "s": "BTCUSDT",
        #                     "pa": "1.5",
        #                     "ep": "50000.00",
        #                     "up": "1500.00",
        #                     "mt": "cross",
        #                     "iw": "0",
        #                     "ps": "BOTH"
        #                 }
        #             ]
        #         }
        #     }
        #
        account = self.safe_dict(message, 'a', {})
        rawPositions = self.safe_list(account, 'P', [])
        if self.positions is None:
            self.positions = ArrayCacheBySymbolById()
        cache = self.positions
        for i in range(0, len(rawPositions)):
            rawPosition = rawPositions[i]
            position = self.parse_ws_position(rawPosition)
            cache.append(position)
        messageHash = 'positions'
        client.resolve(cache, messageHash)

    def parse_ws_position(self, position, market=None):
        #
        #     {
        #         "s": "BTCUSDT",
        #         "pa": "1.5",
        #         "ep": "50000.00",
        #         "up": "1500.00",
        #         "mt": "cross",
        #         "iw": "0",
        #         "ps": "BOTH"
        #     }
        #
        marketId = self.safe_string(position, 's')
        market = self.safe_market(marketId, market)
        symbol = market['symbol']
        contracts = self.safe_string(position, 'pa')
        entryPrice = self.safe_string(position, 'ep')
        unrealizedPnl = self.safe_string(position, 'up')
        marginType = self.safe_string(position, 'mt')
        side = self.safe_string(position, 'ps')
        return self.safe_position({
            'info': position,
            'id': None,
            'symbol': symbol,
            'contracts': contracts,
            'contractSize': None,
            'unrealizedPnl': unrealizedPnl,
            'leverage': None,
            'liquidationPrice': None,
            'collateral': None,
            'notional': None,
            'markPrice': None,
            'entryPrice': entryPrice,
            'timestamp': None,
            'initialMargin': None,
            'initialMarginPercentage': None,
            'maintenanceMargin': None,
            'maintenanceMarginPercentage': None,
            'marginRatio': None,
            'datetime': None,
            'marginMode': marginType,
            'side': side,
            'hedged': None,
            'percentage': None,
        })

    async def authenticate(self, params={}):
        response = await self.fapiPrivatePostListenKey(params)
        listenKey = self.safe_string(response, 'listenKey')
        self.options['listenKey'] = listenKey
        refreshRate = self.safe_integer(self.options, 'listenKeyRefreshRate', 1200000)
        self.delay(refreshRate, self.keep_alive_listen_key, params)
        return listenKey

    async def keep_alive_listen_key(self, params={}):
        await self.fapiPrivatePutListenKey(params)
        refreshRate = self.safe_integer(self.options, 'listenKeyRefreshRate', 1200000)
        self.delay(refreshRate, self.keep_alive_listen_key, params)

    def handle_message(self, client: Client, message):
        #
        #     {
        #         "e": "depthUpdate",
        #         "s": "BTCUSDT",
        #         ...
        #     }
        #
        #     PONG response:
        #     {
        #         "result": {}
        #     }
        #
        # Handle PONG response - Binance-style API returns {"result": {}} for PING
        result = self.safe_value(message, 'result')
        if result is not None:
            eventType = self.safe_string(message, 'e')
            id = self.safe_string(message, 'id')
            # If no event and no id, self is a PONG response
            if eventType is None and id is None:
                self.handle_pong(client, message)
                return
        event = self.safe_string(message, 'e')
        methods: dict = {
            'depthUpdate': self.handle_order_book,
            'aggTrade': self.handle_trades,
            '24hrTicker': self.handle_ticker,
            'kline': self.handle_ohlcv,
            'ACCOUNT_UPDATE': self.handle_account_update,
            'ORDER_TRADE_UPDATE': self.handle_order_update,
        }
        exacMethod = self.safe_value(methods, event)
        if exacMethod is not None:
            exacMethod(client, message)
            return
        data = self.safe_list(message, 'data')
        if data is not None:
            self.handle_tickers(client, message)

    def handle_account_update(self, client: Client, message):
        account = self.safe_dict(message, 'a', {})
        hasBalances = ('B' in account)
        hasPositions = ('P' in account)
        if hasBalances:
            self.handle_balance(client, message)
        if hasPositions:
            self.handle_position(client, message)

    def handle_order_update(self, client: Client, message):
        orderData = self.safe_dict(message, 'o', {})
        executionType = self.safe_string(orderData, 'x')
        if executionType == 'TRADE':
            self.handle_my_trade(client, message)
        self.handle_order(client, message)

    def ping(self, client: Client):
        return {
            'method': 'PING',
        }

    def handle_pong(self, client: Client, message):
        client.lastPong = self.milliseconds()
        return message

    def handle_error_message(self, client: Client, message):
        return message

    def request_id(self):
        requestId = self.sum(self.safe_integer(self.options, 'requestId', 0), 1)
        self.options['requestId'] = requestId
        return requestId
