# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.binanceusdm import binanceusdm
from ccxt.abstract.aster import ImplicitAPI
from ccxt.base.types import Any


class aster(binanceusdm, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(aster, self).describe(), {
            'id': 'aster',
            'name': 'Aster',
            'countries': ['SG'],  # Singapore-based
            'rateLimit': 50,
            'certified': False,
            'pro': True,
            'has': {
                'CORS': None,
                'spot': False,  # Aster only has futures API accessible
                'margin': False,
                'swap': True,
                'future': True,
                'option': False,
                'borrowCrossMargin': False,
                'borrowIsolatedMargin': False,
                'createConvertTrade': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistory': False,
                'fetchConvertCurrencies': False,
                'fetchConvertQuote': False,
                'fetchConvertTrade': False,
                'fetchConvertTradeHistory': False,
                'fetchCrossBorrowRate': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchDepositWithdrawFees': False,
                'fetchIsolatedBorrowRates': False,
                'fetchTransfers': False,
                'fetchWithdrawals': False,
                'repayCrossMargin': False,
                'repayIsolatedMargin': False,
                'transfer': False,
                'withdraw': False,
            },
            'urls': {
                'logo': 'https://static.asterdexstatic.com/cloud-futures/static/images/aster/logo.svg',
                'api': {
                    # Futures API endpoints only - no spot API available
                    'fapiPublic': 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPublicV2': 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPublicV3': 'https://fapi.asterdex.com/fapi/v3',
                    'fapiPrivate': 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPrivateV2': 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPrivateV3': 'https://fapi.asterdex.com/fapi/v3',
                    'fapiData': 'https://fapi.asterdex.com/futures/data',
                },
                'www': 'https://www.asterdex.com/en/referral/49A4aD',
                'referral': {
                    'url': 'https://www.asterdex.com/en/referral/49A4aD',
                    'discount': 0.1,
                },
                'doc': [
                    'https://docs.asterdex.com/product/aster-perpetual-pro/api/api-documentation',
                    'https://github.com/asterdex/api-docs',
                ],
                'fees': 'https://www.asterdex.com/fees',
            },
            'fees': {
                'trading': {
                    'tierBased': True,
                    'percentage': True,
                    'taker': self.parse_number('0.0005'),  # 0.05%
                    'maker': self.parse_number('0.0002'),  # 0.02%
                },
            },
            'options': {
                'fetchMarkets': {
                    'types': ['linear'],  # Only linear perpetuals
                },
                'defaultSubType': 'linear',
                'leverageBrackets': None,
                'marginTypes': {},
                'marginModes': {},
                # Aster-specific options
                'recvWindow': 5000,
                'adjustForTimeDifference': True,
                'defaultTimeInForce': 'GTC',
                'warnOnFetchOpenOrdersWithoutSymbol': True,
            },
        })
