// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import _binanceusdm from '../binanceusdm.js';

// Aster inherits all API methods from binanceusdm since it uses the same API structure
// Futures-only exchange
interface binanceusdm {
    // Market Data Endpoints
    fapiPublicGetPing (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetTime (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetExchangeInfo (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetDepth (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetTrades (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetHistoricalTrades (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetAggTrades (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetKlines (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetContinuousKlines (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetMarkPriceKlines (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetIndexPriceKlines (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetPremiumIndexKlines (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetFundingRate (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetFundingInfo (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetPremiumIndex (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetTicker24hr (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetTickerPrice (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetTickerBookTicker (params?: {}): Promise<implicitReturnType>;
    fapiPublicGetOpenInterest (params?: {}): Promise<implicitReturnType>;
    // Account/Trading Endpoints (Private)
    fapiPrivateGetForceOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetAllOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetOpenOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetOpenOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetAccount (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetBalance (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetLeverageBracket (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetPositionMarginHistory (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetPositionRisk (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetPositionSideDual (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetUserTrades (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetIncome (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetCommissionRate (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetRateLimitOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetMultiAssetsMargin (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetAdlQuantile (params?: {}): Promise<implicitReturnType>;
    fapiPrivateGetOrderAmendment (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostBatchOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostPositionSideDual (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostPositionMargin (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostMarginType (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostLeverage (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostListenKey (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostCountdownCancelAll (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePostMultiAssetsMargin (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePutListenKey (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePutOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivatePutBatchOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateDeleteBatchOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateDeleteOrder (params?: {}): Promise<implicitReturnType>;
    fapiPrivateDeleteAllOpenOrders (params?: {}): Promise<implicitReturnType>;
    fapiPrivateDeleteListenKey (params?: {}): Promise<implicitReturnType>;
    // V2 Endpoints
    fapiPublicV2GetTickerPrice (params?: {}): Promise<implicitReturnType>;
    fapiPrivateV2GetAccount (params?: {}): Promise<implicitReturnType>;
    fapiPrivateV2GetBalance (params?: {}): Promise<implicitReturnType>;
    fapiPrivateV2GetPositionRisk (params?: {}): Promise<implicitReturnType>;
    // Spot API Endpoints
    publicGetPing (params?: {}): Promise<implicitReturnType>;
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    publicGetDepth (params?: {}): Promise<implicitReturnType>;
    publicGetTrades (params?: {}): Promise<implicitReturnType>;
    publicGetAggTrades (params?: {}): Promise<implicitReturnType>;
    publicGetKlines (params?: {}): Promise<implicitReturnType>;
    publicGetTicker24hr (params?: {}): Promise<implicitReturnType>;
    publicGetTickerPrice (params?: {}): Promise<implicitReturnType>;
    publicGetTickerBookTicker (params?: {}): Promise<implicitReturnType>;
    publicGetExchangeInfo (params?: {}): Promise<implicitReturnType>;
    privateGetAccount (params?: {}): Promise<implicitReturnType>;
    privateGetOpenOrders (params?: {}): Promise<implicitReturnType>;
    privateGetAllOrders (params?: {}): Promise<implicitReturnType>;
    privateGetMyTrades (params?: {}): Promise<implicitReturnType>;
    privatePostOrder (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrder (params?: {}): Promise<implicitReturnType>;
}
abstract class binanceusdm extends _binanceusdm {}

export default binanceusdm
