<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\aster as binanceusdm;

class aster extends binanceusdm {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'aster',
            'name' => 'Aster',
            'countries' => array( 'SG' ), // Singapore-based
            'rateLimit' => 50,
            'certified' => false,
            'pro' => true,
            'has' => array(
                'CORS' => null,
                'spot' => false, // Aster only has futures API accessible
                'margin' => false,
                'swap' => true,
                'future' => true,
                'option' => false,
                'borrowCrossMargin' => false,
                'borrowIsolatedMargin' => false,
                'createConvertTrade' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistory' => false,
                'fetchConvertCurrencies' => false,
                'fetchConvertQuote' => false,
                'fetchConvertTrade' => false,
                'fetchConvertTradeHistory' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDeposits' => false,
                'fetchDepositWithdrawFees' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchTransfers' => false,
                'fetchWithdrawals' => false,
                'repayCrossMargin' => false,
                'repayIsolatedMargin' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'urls' => array(
                'logo' => 'https://static.asterdexstatic.com/cloud-futures/static/images/aster/logo.svg',
                'api' => array(
                    // Futures API endpoints only - no spot API available
                    'fapiPublic' => 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPublicV2' => 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPublicV3' => 'https://fapi.asterdex.com/fapi/v3',
                    'fapiPrivate' => 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPrivateV2' => 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPrivateV3' => 'https://fapi.asterdex.com/fapi/v3',
                    'fapiData' => 'https://fapi.asterdex.com/futures/data',
                ),
                'www' => 'https://www.asterdex.com/en/referral/49A4aD',
                'referral' => array(
                    'url' => 'https://www.asterdex.com/en/referral/49A4aD',
                    'discount' => 0.1,
                ),
                'doc' => array(
                    'https://docs.asterdex.com/product/aster-perpetual-pro/api/api-documentation',
                    'https://github.com/asterdex/api-docs',
                ),
                'fees' => 'https://www.asterdex.com/fees',
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => true,
                    'percentage' => true,
                    'taker' => $this->parse_number('0.0005'), // 0.05%
                    'maker' => $this->parse_number('0.0002'), // 0.02%
                ),
            ),
            'options' => array(
                'fetchMarkets' => array(
                    'types' => array( 'linear' ), // Only linear perpetuals
                ),
                'defaultSubType' => 'linear',
                'leverageBrackets' => null,
                'marginTypes' => array(),
                'marginModes' => array(),
                // Aster-specific options
                'recvWindow' => 5000,
                'adjustForTimeDifference' => true,
                'defaultTimeInForce' => 'GTC',
                'warnOnFetchOpenOrdersWithoutSymbol' => true,
            ),
        ));
    }
}
