<?php

namespace ccxt\pro;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use \React\Async;
use \React\Promise\PromiseInterface;

class aster extends \ccxt\async\aster {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'has' => array(
                'ws' => true,
                'watchBalance' => true,
                'watchMyTrades' => true,
                'watchOHLCV' => true,
                'watchOrderBook' => true,
                'watchOrders' => true,
                'watchPositions' => true,
                'watchTicker' => true,
                'watchTickers' => true,
                'watchTrades' => true,
                'watchTradesForSymbols' => true,
            ),
            'urls' => array(
                'api' => array(
                    'ws' => 'wss://fstream.asterdex.com/ws',
                ),
            ),
            'options' => array(
                'tradesLimit' => 1000,
                'ordersLimit' => 1000,
                'OHLCVLimit' => 1000,
                'watchOrderBookRate' => 100,
                'watchOrderBookLimit' => 1000,
                'listenKeyRefreshRate' => 1200000,
                'ws' => array(
                    'cost' => 1,
                ),
            ),
            'streaming' => array(
                'keepAlive' => 30000,
                'ping' => array($this, 'ping'),
            ),
        ));
    }

    public function watch_order_book(string $symbol, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $limit, $params) {
            /**
             * watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
             * @param {string} $symbol unified $symbol of the $market to fetch the order book for
             * @param {int} [$limit] the maximum amount of order book entries to return
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} A dictionary of ~@link https://docs.ccxt.com/#/?id=order-book-structure order book structures~ indexed by $market symbols
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $url = $this->urls['api']['ws'];
            $marketId = $market['id'];
            $messageHash = 'orderbook:' . $symbol;
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => array(
                    strtolower($marketId) . '@depth@100ms',
                ),
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            $orderbook = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            return $orderbook->limit ();
        }) ();
    }

    public function handle_order_book(Client $client, $message) {
        //
        //     {
        //         "e" => "depthUpdate",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "U" => 12345678,
        //         "u" => 12345679,
        //         "b" => [
        //             ["50000.00", "1.5"]
        //         ],
        //         "a" => [
        //             ["50100.00", "0.5"]
        //         ]
        //     }
        //
        $marketId = $this->safe_string($message, 's');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $timestamp = $this->safe_integer($message, 'E');
        $bids = $this->safe_list($message, 'b', array());
        $asks = $this->safe_list($message, 'a', array());
        $snapshot = $this->parse_order_book(array(
            'bids' => $bids,
            'asks' => $asks,
        ), $symbol, $timestamp);
        if (!(is_array($this->orderbooks) && array_key_exists($symbol, $this->orderbooks))) {
            $ob = $this->order_book($snapshot);
            $this->orderbooks[$symbol] = $ob;
        }
        $orderbook = $this->orderbooks[$symbol];
        $orderbook->reset ($snapshot);
        $messageHash = 'orderbook:' . $symbol;
        $client->resolve ($orderbook, $messageHash);
    }

    public function watch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * watches information on multiple $trades made in a $market
             * @param {string} $symbol unified $market $symbol of the $market $trades were made in
             * @param {int} [$since] the earliest time in ms to fetch $trades for
             * @param {int} [$limit] the maximum number of trade structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $url = $this->urls['api']['ws'];
            $marketId = $market['id'];
            $messageHash = 'trades:' . $symbol;
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => array(
                    strtolower($marketId) . '@aggTrade',
                ),
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            $trades = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            if ($this->newUpdates) {
                $limit = $trades->getLimit ($symbol, $limit);
            }
            return $this->filter_by_symbol_since_limit($trades, $symbol, $since, $limit, true);
        }) ();
    }

    public function watch_trades_for_symbols(array $symbols, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $since, $limit, $params) {
            /**
             * watches information on multiple $trades made in multiple markets
             * @param {string[]} $symbols unified $market $symbols of the markets $trades were made in
             * @param {int} [$since] the earliest time in ms to fetch $trades for
             * @param {int} [$limit] the maximum number of trade structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
             */
            Async\await($this->load_markets());
            $symbols = $this->market_symbols($symbols);
            $url = $this->urls['api']['ws'];
            $messageHashes = array();
            $subscriptions = array();
            for ($i = 0; $i < count($symbols); $i++) {
                $symbol = $symbols[$i];
                $market = $this->market($symbol);
                $marketId = $market['id'];
                $messageHash = 'trades:' . $symbol;
                $messageHashes[] = $messageHash;
                $subscriptions[] = strtolower($marketId) . '@aggTrade';
            }
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => $subscriptions,
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            $trades = Async\await($this->watch_multiple($url, $messageHashes, $message, $messageHashes));
            if ($this->newUpdates) {
                $first = $this->safe_dict($trades, 0);
                $tradeSymbol = $this->safe_string($first, 'symbol');
                $limit = $trades->getLimit ($tradeSymbol, $limit);
            }
            return $this->filter_by_symbols_since_limit($trades, $symbols, $since, $limit, true);
        }) ();
    }

    public function handle_trades(Client $client, $message) {
        //
        //     {
        //         "e" => "aggTrade",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "a" => 12345,
        //         "p" => "50000.00",
        //         "q" => "1.5",
        //         "f" => 12344,
        //         "l" => 12345,
        //         "T" => 1638747327000,
        //         "m" => false
        //     }
        //
        $marketId = $this->safe_string($message, 's');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $trade = $this->parse_ws_trade($message, $market);
        $messageHash = 'trades:' . $symbol;
        $tradesArray = $this->safe_value($this->trades, $symbol);
        if ($tradesArray === null) {
            $limit = $this->safe_integer($this->options, 'tradesLimit', 1000);
            $tradesArray = new ArrayCache ($limit);
            $this->trades[$symbol] = $tradesArray;
        }
        $tradesArray->append ($trade);
        $client->resolve ($tradesArray, $messageHash);
    }

    public function parse_ws_trade($trade, $market = null) {
        //
        //     {
        //         "e" => "aggTrade",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "a" => 12345,
        //         "p" => "50000.00",
        //         "q" => "1.5",
        //         "f" => 12344,
        //         "l" => 12345,
        //         "T" => 1638747327000,
        //         "m" => false
        //     }
        //
        $id = $this->safe_string($trade, 'a');
        $timestamp = $this->safe_integer($trade, 'T');
        $price = $this->safe_string($trade, 'p');
        $amount = $this->safe_string($trade, 'q');
        $marketId = $this->safe_string($trade, 's');
        $market = $this->safe_market($marketId, $market);
        $symbol = $market['symbol'];
        $side = $this->safe_value($trade, 'm') ? 'sell' : 'buy';
        return $this->safe_trade(array(
            'info' => $trade,
            'id' => $id,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'type' => null,
            'side' => $side,
            'order' => null,
            'takerOrMaker' => null,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'fee' => null,
        ), $market);
    }

    public function watch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            /**
             * watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
             * @param {string} $symbol unified $symbol of the $market to fetch the ticker for
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $url = $this->urls['api']['ws'];
            $marketId = $market['id'];
            $messageHash = 'ticker:' . $symbol;
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => array(
                    strtolower($marketId) . '@ticker',
                ),
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            return Async\await($this->watch($url, $messageHash, $message, $messageHash));
        }) ();
    }

    public function watch_tickers(?array $symbols = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            /**
             * watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
             * @param {string[]} $symbols unified symbol of the market to fetch the ticker for
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
             */
            Async\await($this->load_markets());
            $symbols = $this->market_symbols($symbols);
            $url = $this->urls['api']['ws'];
            $messageHash = 'tickers';
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => array(
                    '!ticker@arr',
                ),
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            $tickers = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            if ($this->newUpdates) {
                return $this->filter_by_array_tickers($tickers, 'symbol', $symbols);
            }
            return $this->tickers;
        }) ();
    }

    public function handle_ticker(Client $client, $message) {
        //
        //     {
        //         "e" => "24hrTicker",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "p" => "1000.00",
        //         "P" => "2.00",
        //         "w" => "49500.00",
        //         "c" => "50000.00",
        //         "Q" => "1.5",
        //         "o" => "49000.00",
        //         "h" => "51000.00",
        //         "l" => "48000.00",
        //         "v" => "10000.0",
        //         "q" => "495000000.0",
        //         "O" => 1638660928000,
        //         "C" => 1638747328000,
        //         "F" => 12340,
        //         "L" => 12345,
        //         "n" => 6
        //     }
        //
        $marketId = $this->safe_string($message, 's');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $ticker = $this->parse_ws_ticker($message, $market);
        $this->tickers[$symbol] = $ticker;
        $messageHash = 'ticker:' . $symbol;
        $client->resolve ($ticker, $messageHash);
    }

    public function handle_tickers(Client $client, $message) {
        //
        //     array(
        //         {
        //             "e" => "24hrTicker",
        //             "E" => 1638747328000,
        //             "s" => "BTCUSDT",
        //             ...
        //         }
        //     )
        //
        $tickers = $this->safe_list($message, 'data', array());
        $parsedTickers = array();
        for ($i = 0; $i < count($tickers); $i++) {
            $ticker = $tickers[$i];
            $marketId = $this->safe_string($ticker, 's');
            $market = $this->safe_market($marketId);
            $symbol = $market['symbol'];
            $parsedTicker = $this->parse_ws_ticker($ticker, $market);
            $this->tickers[$symbol] = $parsedTicker;
            $parsedTickers[$symbol] = $parsedTicker;
        }
        $messageHash = 'tickers';
        $client->resolve ($this->tickers, $messageHash);
    }

    public function parse_ws_ticker($ticker, $market = null): array {
        //
        //     {
        //         "e" => "24hrTicker",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "p" => "1000.00",
        //         "P" => "2.00",
        //         "w" => "49500.00",
        //         "c" => "50000.00",
        //         "Q" => "1.5",
        //         "o" => "49000.00",
        //         "h" => "51000.00",
        //         "l" => "48000.00",
        //         "v" => "10000.0",
        //         "q" => "495000000.0",
        //         "O" => 1638660928000,
        //         "C" => 1638747328000,
        //         "F" => 12340,
        //         "L" => 12345,
        //         "n" => 6
        //     }
        //
        $timestamp = $this->safe_integer($ticker, 'E');
        $marketId = $this->safe_string($ticker, 's');
        $market = $this->safe_market($marketId, $market);
        $symbol = $market['symbol'];
        $last = $this->safe_string($ticker, 'c');
        $open = $this->safe_string($ticker, 'o');
        $high = $this->safe_string($ticker, 'h');
        $low = $this->safe_string($ticker, 'l');
        $baseVolume = $this->safe_string($ticker, 'v');
        $quoteVolume = $this->safe_string($ticker, 'q');
        $change = $this->safe_string($ticker, 'p');
        $percentage = $this->safe_string($ticker, 'P');
        $vwap = $this->safe_string($ticker, 'w');
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $high,
            'low' => $low,
            'bid' => null,
            'bidVolume' => null,
            'ask' => null,
            'askVolume' => null,
            'vwap' => $vwap,
            'open' => $open,
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => $change,
            'percentage' => $percentage,
            'average' => null,
            'baseVolume' => $baseVolume,
            'quoteVolume' => $quoteVolume,
            'info' => $ticker,
        ), $market);
    }

    public function watch_ohlcv(string $symbol, $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            /**
             * watches historical candlestick data containing the open, high, low, and close price, and the volume of a $market
             * @param {string} $symbol unified $symbol of the $market to fetch OHLCV data for
             * @param {string} $timeframe the length of time each candle represents
             * @param {int} [$since] timestamp in ms of the earliest candle to fetch
             * @param {int} [$limit] the maximum amount of candles to fetch
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {int[][]} A list of candles ordered, open, high, low, close, volume
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $symbol = $market['symbol'];
            $url = $this->urls['api']['ws'];
            $marketId = $market['id'];
            $interval = $this->safe_string($this->timeframes, $timeframe, $timeframe);
            $messageHash = 'ohlcv:' . $timeframe . ':' . $symbol;
            $request = array(
                'method' => 'SUBSCRIBE',
                'params' => array(
                    strtolower($marketId) . '@kline_' . $interval,
                ),
                'id' => $this->request_id(),
            );
            $message = $this->extend($request, $params);
            $ohlcv = Async\await($this->watch($url, $messageHash, $message, $messageHash));
            if ($this->newUpdates) {
                $limit = $ohlcv->getLimit ($symbol, $limit);
            }
            return $this->filter_by_since_limit($ohlcv, $since, $limit, 0, true);
        }) ();
    }

    public function handle_ohlcv(Client $client, $message) {
        //
        //     {
        //         "e" => "kline",
        //         "E" => 1638747328000,
        //         "s" => "BTCUSDT",
        //         "k" => {
        //             "t" => 1638747300000,
        //             "T" => 1638747359999,
        //             "s" => "BTCUSDT",
        //             "i" => "1m",
        //             "f" => 12340,
        //             "L" => 12345,
        //             "o" => "49000.00",
        //             "c" => "50000.00",
        //             "h" => "51000.00",
        //             "l" => "48000.00",
        //             "v" => "10000.0",
        //             "n" => 6,
        //             "x" => false,
        //             "q" => "495000000.0",
        //             "V" => "5000.0",
        //             "Q" => "247500000.0"
        //         }
        //     }
        //
        $kline = $this->safe_dict($message, 'k', array());
        $marketId = $this->safe_string($kline, 's');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $interval = $this->safe_string($kline, 'i');
        $timeframe = $this->find_timeframe($interval);
        $parsed = array(
            $this->safe_integer($kline, 't'),
            $this->safe_number($kline, 'o'),
            $this->safe_number($kline, 'h'),
            $this->safe_number($kline, 'l'),
            $this->safe_number($kline, 'c'),
            $this->safe_number($kline, 'v'),
        );
        $messageHash = 'ohlcv:' . $timeframe . ':' . $symbol;
        $this->ohlcvs[$symbol] = $this->safe_dict($this->ohlcvs, $symbol, array());
        $stored = $this->safe_value($this->ohlcvs[$symbol], $timeframe);
        if ($stored === null) {
            $limit = $this->safe_integer($this->options, 'OHLCVLimit', 1000);
            $stored = new ArrayCacheByTimestamp ($limit);
            $this->ohlcvs[$symbol][$timeframe] = $stored;
        }
        $stored->append ($parsed);
        $client->resolve ($stored, $messageHash);
    }

    public function watch_balance($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * watch balance and get the amount of funds available for trading or funds locked in orders
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=balance-structure balance structure~
             */
            Async\await($this->load_markets());
            Async\await($this->authenticate($params));
            $url = $this->urls['api']['ws'];
            $listenKey = $this->safe_string($this->options, 'listenKey');
            $messageHash = 'balance';
            return Async\await($this->watch($url . '/' . $listenKey, $messageHash, null, $messageHash));
        }) ();
    }

    public function handle_balance(Client $client, $message) {
        //
        //     {
        //         "e" => "ACCOUNT_UPDATE",
        //         "E" => 1638747328000,
        //         "a" => {
        //             "B" => array(
        //                 {
        //                     "a" => "USDT",
        //                     "wb" => "10000.00000000",
        //                     "cw" => "9500.00000000"
        //                 }
        //             )
        //         }
        //     }
        //
        $accountData = $this->safe_dict($message, 'a', array());
        $balances = $this->safe_list($accountData, 'B', array());
        for ($i = 0; $i < count($balances); $i++) {
            $balance = $balances[$i];
            $currencyId = $this->safe_string($balance, 'a');
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account();
            $account['free'] = $this->safe_string($balance, 'cw');
            $account['total'] = $this->safe_string($balance, 'wb');
            $this->balance[$code] = $account;
        }
        $this->balance = $this->safe_balance($this->balance);
        $messageHash = 'balance';
        $client->resolve ($this->balance, $messageHash);
    }

    public function watch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * watches information on multiple $orders made by the user
             * @param {string} $symbol unified market $symbol of the market $orders were made in
             * @param {int} [$since] the earliest time in ms to fetch $orders for
             * @param {int} [$limit] the maximum number of order structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
             */
            Async\await($this->load_markets());
            Async\await($this->authenticate($params));
            $url = $this->urls['api']['ws'];
            $listenKey = $this->safe_string($this->options, 'listenKey');
            $messageHash = 'orders';
            if ($symbol !== null) {
                $symbol = $this->symbol($symbol);
                $messageHash .= ':' . $symbol;
            }
            $orders = Async\await($this->watch($url . '/' . $listenKey, $messageHash, null, $messageHash));
            if ($this->newUpdates) {
                $limit = $orders->getLimit ($symbol, $limit);
            }
            return $this->filter_by_symbol_since_limit($orders, $symbol, $since, $limit, true);
        }) ();
    }

    public function handle_order(Client $client, $message) {
        //
        //     {
        //         "e" => "ORDER_TRADE_UPDATE",
        //         "E" => 1638747328000,
        //         "o" => {
        //             "s" => "BTCUSDT",
        //             "c" => "client_order_id",
        //             "S" => "BUY",
        //             "o" => "LIMIT",
        //             "f" => "GTC",
        //             "q" => "1.5",
        //             "p" => "50000.00",
        //             "ap" => "0",
        //             "sp" => "0",
        //             "x" => "NEW",
        //             "X" => "NEW",
        //             "i" => 12345,
        //             "l" => "0",
        //             "z" => "0",
        //             "L" => "0",
        //             "T" => 1638747327000,
        //             "t" => 0
        //         }
        //     }
        //
        $orderData = $this->safe_dict($message, 'o', array());
        $order = $this->parse_ws_order($orderData);
        $symbol = $order['symbol'];
        if ($this->orders === null) {
            $limit = $this->safe_integer($this->options, 'ordersLimit', 1000);
            $this->orders = new ArrayCacheBySymbolById ($limit);
        }
        $orders = $this->orders;
        $orders->append ($order);
        $messageHash = 'orders';
        $client->resolve ($orders, $messageHash);
        $messageHash .= ':' . $symbol;
        $client->resolve ($orders, $messageHash);
    }

    public function parse_ws_order($order, $market = null) {
        //
        //     {
        //         "s" => "BTCUSDT",
        //         "c" => "client_order_id",
        //         "S" => "BUY",
        //         "o" => "LIMIT",
        //         "f" => "GTC",
        //         "q" => "1.5",
        //         "p" => "50000.00",
        //         "ap" => "0",
        //         "sp" => "0",
        //         "x" => "NEW",
        //         "X" => "NEW",
        //         "i" => 12345,
        //         "l" => "0",
        //         "z" => "0",
        //         "L" => "0",
        //         "T" => 1638747327000,
        //         "t" => 0
        //     }
        //
        $id = $this->safe_string($order, 'i');
        $clientOrderId = $this->safe_string($order, 'c');
        $marketId = $this->safe_string($order, 's');
        $market = $this->safe_market($marketId, $market);
        $symbol = $market['symbol'];
        $side = $this->safe_string_lower($order, 'S');
        $type = $this->safe_string_lower($order, 'o');
        $price = $this->safe_string($order, 'p');
        $amount = $this->safe_string($order, 'q');
        $filled = $this->safe_string($order, 'z');
        $average = $this->safe_string($order, 'ap');
        $timestamp = $this->safe_integer($order, 'T');
        $rawStatus = $this->safe_string($order, 'X');
        $status = $this->parse_order_status($rawStatus);
        $timeInForce = $this->safe_string($order, 'f');
        return $this->safe_order(array(
            'info' => $order,
            'id' => $id,
            'clientOrderId' => $clientOrderId,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => null,
            'symbol' => $symbol,
            'type' => $type,
            'side' => $side,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'average' => $average,
            'filled' => $filled,
            'remaining' => null,
            'status' => $status,
            'fee' => null,
            'trades' => null,
            'timeInForce' => $timeInForce,
            'postOnly' => null,
            'reduceOnly' => null,
        ), $market);
    }

    public function watch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * watches information on multiple $trades made by the user
             * @param {string} $symbol unified market $symbol of the market $trades were made in
             * @param {int} [$since] the earliest time in ms to fetch $trades for
             * @param {int} [$limit] the maximum number of trade structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=trade-structure trade structures~
             */
            Async\await($this->load_markets());
            Async\await($this->authenticate($params));
            $url = $this->urls['api']['ws'];
            $listenKey = $this->safe_string($this->options, 'listenKey');
            $messageHash = 'myTrades';
            if ($symbol !== null) {
                $symbol = $this->symbol($symbol);
                $messageHash .= ':' . $symbol;
            }
            $trades = Async\await($this->watch($url . '/' . $listenKey, $messageHash, null, $messageHash));
            if ($this->newUpdates) {
                $limit = $trades->getLimit ($symbol, $limit);
            }
            return $this->filter_by_symbol_since_limit($trades, $symbol, $since, $limit, true);
        }) ();
    }

    public function handle_my_trade(Client $client, $message) {
        //
        //     {
        //         "e" => "ORDER_TRADE_UPDATE",
        //         "E" => 1638747328000,
        //         "o" => {
        //             "s" => "BTCUSDT",
        //             "c" => "client_order_id",
        //             "S" => "BUY",
        //             "o" => "LIMIT",
        //             "f" => "GTC",
        //             "q" => "1.5",
        //             "p" => "50000.00",
        //             "x" => "TRADE",
        //             "X" => "PARTIALLY_FILLED",
        //             "i" => 12345,
        //             "l" => "1.0",
        //             "z" => "1.0",
        //             "L" => "50000.00",
        //             "n" => "10.00",
        //             "N" => "USDT",
        //             "T" => 1638747327000,
        //             "t" => 67890
        //         }
        //     }
        //
        $orderData = $this->safe_dict($message, 'o', array());
        $executionType = $this->safe_string($orderData, 'x');
        if ($executionType !== 'TRADE') {
            return;
        }
        $trade = $this->parse_ws_my_trade($orderData);
        $symbol = $trade['symbol'];
        if ($this->myTrades === null) {
            $limit = $this->safe_integer($this->options, 'tradesLimit', 1000);
            $this->myTrades = new ArrayCacheBySymbolById ($limit);
        }
        $myTrades = $this->myTrades;
        $myTrades->append ($trade);
        $messageHash = 'myTrades';
        $client->resolve ($myTrades, $messageHash);
        $messageHash .= ':' . $symbol;
        $client->resolve ($myTrades, $messageHash);
    }

    public function parse_ws_my_trade($trade, $market = null) {
        //
        //     {
        //         "s" => "BTCUSDT",
        //         "c" => "client_order_id",
        //         "S" => "BUY",
        //         "o" => "LIMIT",
        //         "l" => "1.0",
        //         "z" => "1.0",
        //         "L" => "50000.00",
        //         "n" => "10.00",
        //         "N" => "USDT",
        //         "T" => 1638747327000,
        //         "t" => 67890,
        //         "i" => 12345
        //     }
        //
        $id = $this->safe_string($trade, 't');
        $orderId = $this->safe_string($trade, 'i');
        $marketId = $this->safe_string($trade, 's');
        $market = $this->safe_market($marketId, $market);
        $symbol = $market['symbol'];
        $side = $this->safe_string_lower($trade, 'S');
        $type = $this->safe_string_lower($trade, 'o');
        $price = $this->safe_string($trade, 'L');
        $amount = $this->safe_string($trade, 'l');
        $timestamp = $this->safe_integer($trade, 'T');
        $feeCost = $this->safe_string($trade, 'n');
        $feeCurrency = $this->safe_currency_code($this->safe_string($trade, 'N'));
        $fee = null;
        if ($feeCost !== null) {
            $fee = array(
                'cost' => $feeCost,
                'currency' => $feeCurrency,
            );
        }
        return $this->safe_trade(array(
            'info' => $trade,
            'id' => $id,
            'order' => $orderId,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'type' => $type,
            'side' => $side,
            'takerOrMaker' => null,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'fee' => $fee,
        ), $market);
    }

    public function watch_positions(?array $symbols = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbols, $since, $limit, $params) {
            /**
             * watch all open $positions
             * @param {string[]} [$symbols] list of unified market $symbols
             * @param {int} [$since] the earliest time in ms to fetch $positions for
             * @param {int} [$limit] the maximum number of $positions to retrieve
             * @param {array} $params extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of {@link https://docs.ccxt.com/en/latest/manual.html#position-structure position structure}
             */
            Async\await($this->load_markets());
            Async\await($this->authenticate($params));
            $url = $this->urls['api']['ws'];
            $listenKey = $this->safe_string($this->options, 'listenKey');
            $messageHash = 'positions';
            $positions = Async\await($this->watch($url . '/' . $listenKey, $messageHash, null, $messageHash));
            return $this->filter_by_symbols_since_limit($positions, $symbols, $since, $limit, true);
        }) ();
    }

    public function handle_position(Client $client, $message) {
        //
        //     {
        //         "e" => "ACCOUNT_UPDATE",
        //         "E" => 1638747328000,
        //         "a" => {
        //             "P" => array(
        //                 {
        //                     "s" => "BTCUSDT",
        //                     "pa" => "1.5",
        //                     "ep" => "50000.00",
        //                     "up" => "1500.00",
        //                     "mt" => "cross",
        //                     "iw" => "0",
        //                     "ps" => "BOTH"
        //                 }
        //             )
        //         }
        //     }
        //
        $account = $this->safe_dict($message, 'a', array());
        $rawPositions = $this->safe_list($account, 'P', array());
        if ($this->positions === null) {
            $this->positions = new ArrayCacheBySymbolById ();
        }
        $cache = $this->positions;
        for ($i = 0; $i < count($rawPositions); $i++) {
            $rawPosition = $rawPositions[$i];
            $position = $this->parse_ws_position($rawPosition);
            $cache->append ($position);
        }
        $messageHash = 'positions';
        $client->resolve ($cache, $messageHash);
    }

    public function parse_ws_position($position, $market = null) {
        //
        //     {
        //         "s" => "BTCUSDT",
        //         "pa" => "1.5",
        //         "ep" => "50000.00",
        //         "up" => "1500.00",
        //         "mt" => "cross",
        //         "iw" => "0",
        //         "ps" => "BOTH"
        //     }
        //
        $marketId = $this->safe_string($position, 's');
        $market = $this->safe_market($marketId, $market);
        $symbol = $market['symbol'];
        $contracts = $this->safe_string($position, 'pa');
        $entryPrice = $this->safe_string($position, 'ep');
        $unrealizedPnl = $this->safe_string($position, 'up');
        $marginType = $this->safe_string($position, 'mt');
        $side = $this->safe_string($position, 'ps');
        return $this->safe_position(array(
            'info' => $position,
            'id' => null,
            'symbol' => $symbol,
            'contracts' => $contracts,
            'contractSize' => null,
            'unrealizedPnl' => $unrealizedPnl,
            'leverage' => null,
            'liquidationPrice' => null,
            'collateral' => null,
            'notional' => null,
            'markPrice' => null,
            'entryPrice' => $entryPrice,
            'timestamp' => null,
            'initialMargin' => null,
            'initialMarginPercentage' => null,
            'maintenanceMargin' => null,
            'maintenanceMarginPercentage' => null,
            'marginRatio' => null,
            'datetime' => null,
            'marginMode' => $marginType,
            'side' => $side,
            'hedged' => null,
            'percentage' => null,
        ));
    }

    public function authenticate($params = array ()) {
        return Async\async(function () use ($params) {
            $response = Async\await($this->fapiPrivatePostListenKey ($params));
            $listenKey = $this->safe_string($response, 'listenKey');
            $this->options['listenKey'] = $listenKey;
            $refreshRate = $this->safe_integer($this->options, 'listenKeyRefreshRate', 1200000);
            $this->delay($refreshRate, array($this, 'keep_alive_listen_key'), $params);
            return $listenKey;
        }) ();
    }

    public function keep_alive_listen_key($params = array ()) {
        return Async\async(function () use ($params) {
            Async\await($this->fapiPrivatePutListenKey ($params));
            $refreshRate = $this->safe_integer($this->options, 'listenKeyRefreshRate', 1200000);
            $this->delay($refreshRate, array($this, 'keep_alive_listen_key'), $params);
        }) ();
    }

    public function handle_message(Client $client, $message) {
        //
        //     {
        //         "e" => "depthUpdate",
        //         "s" => "BTCUSDT",
        //         ...
        //     }
        //
        //     PONG response:
        //     {
        //         "result" => array()
        //     }
        //
        // Handle PONG response - Binance-style API returns array("result" => array()) for PING
        $result = $this->safe_value($message, 'result');
        if ($result !== null) {
            $eventType = $this->safe_string($message, 'e');
            $id = $this->safe_string($message, 'id');
            // If no $event and no $id, this is a PONG response
            if ($eventType === null && $id === null) {
                $this->handle_pong($client, $message);
                return;
            }
        }
        $event = $this->safe_string($message, 'e');
        $methods = array(
            'depthUpdate' => array($this, 'handle_order_book'),
            'aggTrade' => array($this, 'handle_trades'),
            '24hrTicker' => array($this, 'handle_ticker'),
            'kline' => array($this, 'handle_ohlcv'),
            'ACCOUNT_UPDATE' => array($this, 'handle_account_update'),
            'ORDER_TRADE_UPDATE' => array($this, 'handle_order_update'),
        );
        $exacMethod = $this->safe_value($methods, $event);
        if ($exacMethod !== null) {
            $exacMethod($client, $message);
            return;
        }
        $data = $this->safe_list($message, 'data');
        if ($data !== null) {
            $this->handle_tickers($client, $message);
        }
    }

    public function handle_account_update(Client $client, $message) {
        $account = $this->safe_dict($message, 'a', array());
        $hasBalances = (is_array($account) && array_key_exists('B', $account));
        $hasPositions = (is_array($account) && array_key_exists('P', $account));
        if ($hasBalances) {
            $this->handle_balance($client, $message);
        }
        if ($hasPositions) {
            $this->handle_position($client, $message);
        }
    }

    public function handle_order_update(Client $client, $message) {
        $orderData = $this->safe_dict($message, 'o', array());
        $executionType = $this->safe_string($orderData, 'x');
        if ($executionType === 'TRADE') {
            $this->handle_my_trade($client, $message);
        }
        $this->handle_order($client, $message);
    }

    public function ping(Client $client) {
        return array(
            'method' => 'PING',
        );
    }

    public function handle_pong(Client $client, $message) {
        $client->lastPong = $this->milliseconds();
        return $message;
    }

    public function handle_error_message(Client $client, $message) {
        return $message;
    }

    public function request_id() {
        $requestId = $this->sum($this->safe_integer($this->options, 'requestId', 0), 1);
        $this->options['requestId'] = $requestId;
        return $requestId;
    }
}
